export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as AllGames } from './AllGames';
export { default as Game } from './Game';
export { default as NoPage } from './NoPage';
export { default as Admin } from './Admin';
export { default as Standings } from './Standings';
export { default as PackagePlan } from './ConfirmData';
